name: Dependant Jobs

#Define when workflow should run
on: [push]

jobs: 
    dependant:
      # add a job that echoes some text, but will not run until the 'depended-on' job runs
        runs-on: ubuntu-latest
        needs: depended-on
        steps:
          - name: second
            run: echo executed second
    depended-on:
      # add a job that echoes some text, and will run before the 'dependant' job runs
        runs-on: ubuntu-latest
        steps:
            - name: first
              run: echo executed first
    